# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chargify_api_ares}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Klett", "The Lab Rats @ Phase Two Labs"]
  s.date = %q{2009-12-06}
  s.description = %q{}
  s.email = %q{mklett@grasshopper.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE.txt",
     "README.md",
     "Rakefile",
     "VERSION",
     "chargify_api_ares.gemspec",
     "lib/chargify_api_ares.rb",
     "samples/customers.rb",
     "samples/products.rb",
     "samples/subscriptions.rb"
  ]
  s.homepage = %q{http://github.com/grasshopperlabs/chargify_api_ares}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Chargify API wrapper for Ruby using ActiveResource}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

